### ISSUE TITLE
Test DSL

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/kubernetes-ipfs#3]
One of my main areas of concern is to have a nice testing DSL to enables reuse and readability so it'll be easy to add new tests and refactor existing ones.

Currently, it looks something like this:

```
name: Simple Add and Cat
config:
  nodes: 2
  times: 10
steps:
  - name: Add file
    on_node: 1
    cmd: head -c 10 /dev/urandom | base64 > /tmp/file.txt && cat /tmp/file.txt && ipfs add -q /tmp/file.txt
    outputs: 
    - line: 0
      save_to: FILE
    - line: 1
      save_to: HASH
  - name: Cat file
    on_node: 2
    inputs:
      - FILE
      - HASH
    cmd: ipfs cat $HASH
    assertions:
    - line: 0
should_be_equal_to: FILE
```

I'm in a rush right now, so I'll leave this here and write my thoughts when I can.
